[build]
builder = "nixpacks"
# Nixpacks will use nixpacks.toml for build commands

[deploy]
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300

[environment]
NODE_ENV = "production"
# Railway provides PORT automatically, don't override it