[build]
builder = "nixpacks"
nixpacksPlan = "nixpacks.toml"
# Force nixpacks to use our configuration

[deploy]
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300

[environment]
NODE_ENV = "production"
# Railway provides PORT automatically, don't override it