[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm build"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300

[environment]
NODE_ENV = "production"
# Railway provides PORT automatically, don't override it