[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm build"

[deploy]
startCommand = "cd apps/web && pnpm start"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300

[environment]
NODE_ENV = "production"
PORT = { fromService = "web" }