[build]
builder = "nixpacks"
buildCommand = "pnpm install && chmod +x scripts/build-with-env.sh && ./scripts/build-with-env.sh"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300

[environment]
NODE_ENV = "production"
# Railway provides PORT automatically, don't override it